documentation:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - 'docs/**'
        - '*.md'
        - '.readthedocs.yaml'
        - 'LICENSE'
      - all-globs-to-any-file:
        - '*.rst'
        - '!CHANGES.rst'

environment:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - 'environment.yaml'

testing:
  - any:
    - changed-files:
      - any-glob-to-any-file:
        - '.github/workflows/build.yaml'
        - 'tests/**'

