image: mambaorg/micromamba:latest

before_script:
  - eval "$(micromamba shell hook --shell=bash)"
  - mkdir -p ./conda/
  - touch .condarc
  - micromamba config append --file .condarc pkgs_dirs ./conda/pkgs
  - micromamba config append --file .condarc envs_dirs ./conda/envs

cache:
  key: cache-$CI_RUNNER_EXECUTABLE_ARCH-$CI_COMMIT_REF_SLUG
  paths:
    - ./conda/

build:
  stage: build
  parallel:
    matrix:
      - PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
  tags:
    - $RUNNER
  script:
    - micromamba create -y -r ./conda/base -c conda-forge -n stenv python=$PYTHON conda gcc -rc-file .condarc
    - micromamba activate stenv
    - conda env export --no-build | grep -v "name:" | grep -v "prefix:"
    - pytest -n auto tests/test_import.py

unit-tests:
  stage: test
  parallel:
    matrix:
      - PACKAGE: acstools
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        EXTRAS: ["test"]
      - PACKAGE: asdf
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        EXTRAS: ["tests"]
      - PACKAGE: ccdproc
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        EXTRAS: ["test"]
      - PACKAGE: costools
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
      - PACKAGE: reftools
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        EXTRAS: ["test"]
      - PACKAGE: synphot
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        EXTRAS: ["test"]
      - PACKAGE: wfpc2tools
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
  tags:
    - $RUNNER
  script:
    - micromamba create -y -r ./conda/base -c conda-forge -n stenv python=$PYTHON conda gcc -rc-file .condarc
    - micromamba activate stenv
    - conda env export --no-build | grep -v "name:" | grep -v "prefix:"
    - pip install $PACKAGE$EXTRAS
    - pytest -n auto --pyargs $PACKAGE $pytest_args

unit-tests-from-source:
  stage: test
  parallel:
    matrix:
      - PACKAGE: calcos
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        REPOSITORY: https://github.com/spacetelescope/calcos
      #- PACKAGE: crds
      #  PYTHON: ["3.9", "3.10", "3.11"]
      #  RUNNER: ["test"]
      #  REPOSITORY: https://github.com/spacetelescope/crds
      #  EXTRAS: [ test ]
      #  env:
      #    CRDS_SERVER_URL: https://hst-crds.stsci.edu
      #  pre_command: './setup_test_cache $HOME && source envs/hst-crds-ops.sh'
      #- PACKAGE: drizzlepac
      #  PYTHON: ["3.9", "3.10", "3.11"]
      #  RUNNER: ["test"]
      #  REPOSITORY: https://github.com/spacetelescope/drizzlepac
      #  EXTRAS: [ test ]
      - PACKAGE: hstcal
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        REPOSITORY: https://github.com/spacetelescope/hstcal
        pytest_args: '--slow'
        test_directory: tests
        CRDS_SERVER_URL: https://hst-crds.stsci.edu
      - PACKAGE: jwst
        PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        REPOSITORY: https://github.com/spacetelescope/jwst
        extras: [ test ]
        pytest_args: '--slow -k "not test_cmdline_status"'
        CRDS_SERVER_URL: https://jwst-crds.stsci.edu
  tags:
    - $RUNNER
  script:
    - micromamba create -y -r ./conda/base -c conda-forge -n stenv python=$PYTHON conda gcc -rc-file .condarc
    - micromamba activate stenv
    - conda env export --no-build | grep -v "name:" | grep -v "prefix:"
    - pip install -e .$EXTRAS
    - pytest -n auto $pytest_args $test_directory

smoke-tests:
  stage: test
  parallel:
    matrix:
      - PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        COMMAND: ["calcos la8n01qkq_rawtag_a.fits", "pytest -n auto tests/test_drizzlepac.py"]
  tags:
    - $RUNNER
  script:
    - micromamba create -y -r ./conda/base -c conda-forge -n stenv python=$PYTHON conda gcc -rc-file .condarc
    - micromamba activate stenv
    - conda env export --no-build | grep -v "name:" | grep -v "prefix:"
    - $COMMAND

version:
  stage: deploy
  script:
    - pip install dunamai
    - export VERSION=$(dunamai from any --pattern "(?P<base>\d+\.\d+\.\d+)")
  artifacts:
    reports:
        #propagates variables into the pipeline level, but never stores the actual file
        dotenv: deploy.env

export:
  stage: deploy
  needs: ["version"]
  parallel:
    matrix:
      - PYTHON: ["3.9", "3.10", "3.11"]
        RUNNER: ["test"]
        COMMAND: ["calcos la8n01qkq_rawtag_a.fits", "pytest -n auto tests/test_drizzlepac.py"]
  tags:
    - $RUNNER
  script:
    - micromamba create -y -r ./conda/base -c conda-forge -n stenv python=$PYTHON conda gcc -rc-file .condarc
    - micromamba activate stenv
    - conda env export --no-build | grep -v "name:" | grep -v "prefix:" > stenv-$CI_RUNNER_EXECUTABLE_ARCH-$PYTHON.yaml
    - cat stenv-$CI_RUNNER_EXECUTABLE_ARCH-$PYTHON.yaml
  artifacts:
    paths:
      - stenv-$CI_RUNNER_EXECUTABLE_ARCH-$PYTHON.yaml
  environment: production
