channels:
  - conda-forge

dependencies:
  - fitsverify
  - hstcal
  - pip
  - pytables
  - python
  - pytest
  - pytest-xdist
  - pip:
      - acstools
      - asdf>=2.12.1
      - astropy
      - calcos>=3.4.4
      - ccdproc
      - ci-watson
      - costools
      - crds
      - dask
      - drizzlepac
      - ginga
      - h5py
      - ipython
      - jupyter
      - jwst>=1.6.2
      - nictools
      - numpy
      - pysynphot
      - reftools
      - scipy
      - sphinx
      - stistools
      - stsynphot
      - stregion>=1.1.7
      - synphot
      - wfc3tools
      - wfpc2tools
