channels:
  - conda-forge

dependencies:
  - astropy
  - dask
  - fitsverify
  - hstcal
  - h5py
  - ipython
  - jupyter
  - numpy
  - pip
  - pkg-config
  - pytables
  - python
  - pytest
  - pytest-xdist
  - scipy
  - scikit-image
  - sphinx
  - pip:
      - acstools
      - asdf>=2.12.1
      - calcos>=3.4.4
      - ccdproc
      - ci-watson
      - costools
      - crds
      - drizzlepac
      - ginga
      - jwst>=1.6.2
      - nictools
      - pysynphot
      - reftools
      - stcal<1.3.4
      - stdatamodels<1.0.0
      - stistools
      - stsynphot
      - stregion>=1.1.7
      - synphot
      - wfc3tools
      - wfpc2tools
