# this is the base unpinned environment for ``stenv``; to manually resolve an environment from this file, run the following: 
# conda env create -n stenv -f https://raw.githubusercontent.com/spacetelescope/stenv/main/environment.yaml 

channels:
  - conda-forge

dependencies:
  - astropy
  - dask
  - fitsverify
  - hstcal
  - h5py
  - ipython
  - jupyter
  - numpy
  - pip
  - pytables
  - python>=3.10
  - pytest
  - pytest-xdist
  - scipy
  - scikit-image
  - sphinx
  - pip:
      - acstools
      - asdf
      - calcos
      - ccdproc
      - ci_watson
      - costools
      - crds
      - drizzlepac
      - ginga
      - jwst
      - nictools
      - pysynphot
      - reftools
      - stcal
      - stdatamodels
      - stistools
      - stsynphot
      - stregion
      - synphot
      - wfc3tools
      - wfpc2tools
