name: Build and test environment

on:
  pull_request:
    branches:
      - main
    paths:
      - 'environment.yml'
      - '.github/workflows/*.yml'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release:
        description: upload exported files to a release of the current tag
        required: false
        type: boolean

defaults:
  run:
    shell: bash -l {0}

env:
  CRDS_PATH: /tmp/crds_cache
  PYSYN_CDBS: /tmp/trds

jobs:
  build:
    name: build Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: environment.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - run: pip freeze
      - run: pytest -n auto tests/test_import.py
  unit_tests:
    name: run `${{ matrix.package }}` unit tests in Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ build ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        package: [ acstools, asdf, ccdproc, costools, reftools, synphot, wfpc2tools ]
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]
        include:
          - package: acstools
            extras: [ test ]
          - package: asdf
            extras: [ tests ]
          - package: ccdproc
            extras: [ test ]
          - package: costools
          #- package: pysynphot
          #  extras: [ test ]
          - package: reftools
            extras: [ test ]
          - package: synphot
            extras: [ test ]
          - package: wfpc2tools
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: environment.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - if: matrix.extras != ''
        run: pip install "${{ matrix.package }}[${{ join(matrix.extras, ',') }}]"
      - run: pip freeze
      - if: matrix.env.CRDS_SERVER_URL != ''
        run: echo "context=$(crds list --operational-context)" >> $GITHUB_OUTPUT
        id: crds-context
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
      - if: steps.crds-context.outputs.context != ''
        uses: actions/cache@v3
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ matrix.package }}-${{ steps.crds-context.outputs.context }}
      - run: pytest -n auto ${{ matrix.pytest_args }} --pyargs ${{ matrix.package }}
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
  unit_tests_from_source:
    name: run `${{ matrix.package }}` unit tests from source in Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ build ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        package: [ calcos, hstcal, jwst, stsynphot ]
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]
        include:
          - package: calcos
            repository: spacetelescope/calcos
          #- package: crds
          #  repository: spacetelescope/crds
          #  extras: [ test ]
          #  env:
          #    CRDS_SERVER_URL: https://hst-crds.stsci.edu
          #  pre_command: './setup_test_cache $HOME && source envs/hst-crds-ops.sh'
          #- package: drizzlepac
          #  repository: spacetelescope/drizzlepac
          #  extras: [ test ]
          - package: hstcal
            repository: spacetelescope/hstcal
            pytest_args: '--slow'
            test_directory: tests
            env:
              CRDS_SERVER_URL: https://hst-crds.stsci.edu
          - package: jwst
            repository: spacetelescope/jwst
            extras: [ test ]
            pytest_args: '--slow'
            env:
              CRDS_SERVER_URL: https://jwst-crds.stsci.edu
          #- package: stistools
          #  repository: spacetelescope/stistools
          - package: stsynphot
            repository: spacetelescope/stsynphot_refactor
            extras: [ test ]
    steps:
      - uses: actions/checkout@v3
        with:
          path: stenv
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: stenv/environment.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - run: echo "version=$(conda list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@v3
        with:
          path: ${{ matrix.package }}
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
      - if: matrix.extras != ''
        run: pip install ".[${{ join(matrix.extras, ',') }}]"
        working-directory: ${{ matrix.package }}
      - run: pip freeze
      - if: matrix.env.CRDS_SERVER_URL != ''
        run: echo "context=$(crds list --operational-context)" >> $GITHUB_OUTPUT
        id: crds-context
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
      - if: steps.crds-context.outputs.context != ''
        uses: actions/cache@v3
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ matrix.package }}-${{ steps.crds-context.outputs.context }}
      - if: matrix.pre_command != ''
        run: ${{ matrix.pre_command }}
        working-directory: ${{ matrix.package }}
      - run: pytest -n auto ${{ matrix.pytest_args }} ${{ matrix.test_directory }}
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
        working-directory: ${{ matrix.package }}
  smoke_tests:
    name: run `${{ matrix.package }}` smoke tests in Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ build ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        package: [ calcos, drizzlepac ]
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]
        include:
          - package: calcos
            run: calcos la8n01qkq_rawtag_a.fits
            env:
              CRDS_SERVER_URL: https://hst-crds.stsci.edu
              jref: hst/references/hst/
          - package: drizzlepac
            run: pytest -n auto tests/test_drizzlepac.py
            env:
              CRDS_SERVER_URL: https://hst-crds.stsci.edu
              jref: hst/references/hst/
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          environment-file: environment.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - if: matrix.extras != ''
        run: pip install ".[${{ join(matrix.extras, ',') }}]"
      - run: pip freeze
      - if: matrix.env.CRDS_SERVER_URL != ''
        run: echo "context=$(crds list --operational-context)" >> $GITHUB_OUTPUT
        id: crds-context
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
      - if: steps.crds-context.outputs.context != ''
        uses: actions/cache@v3
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ matrix.package }}-${{ steps.crds-context.outputs.context }}
      - uses: actions/cache@v3
        with:
          path: 'tests/data/'
          key: data-${{ hashFiles('tests/data/*') }}
      - run: ${{ matrix.run }}
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
          jref: ${{ env.CRDS_PATH }}/${{ matrix.env.jref }}
  export:
    name: export Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ unit_tests, unit_tests_from_source, smoke_tests ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: mtkennerly/dunamai-action@v1
        id: version
        with:
          args: --pattern "(?P<base>\d+\.\d+\.\d+)"
      # TODO: change following to `provision-with-micromamba` after https://github.com/mamba-org/mamba/issues/2008
      - run: echo "::set-output name=date::$(date +'%a %b %d %Y')"
        id: date
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: stenv-${{ runner.os }}-py${{ matrix.python-version }}
          python-version: ${{ matrix.python-version }}
          miniforge-version: 'latest'
          miniforge-variant: 'Mambaforge'
          use-mamba: true
          channels: 'conda-forge,defaults'
          channel-priority: true
          use-only-tar-bz2: true
      - uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: "mamba-env ${{ runner.os }}-${{ runner.arch }} ${{ steps.date.outputs.date }} file: ${{ hashFiles('environment.yml') }}"
      - run: conda env export --no-build > stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
      # TODO: change previous to `provision-with-micromamba` after https://github.com/mamba-org/mamba/issues/2008
      - run: |
          sed -i"" "/name:/d" stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
          sed -i"" "/prefix:/d" stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
      - run: cat stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
      - uses: actions/upload-artifact@v3
        with:
          name: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
          path: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
      - if: (github.event_name == 'release' && github.event.action == 'published') || github.event.inputs.release == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          file: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}.yml
  update_docs:
    if: (github.event_name == 'release' && github.event.action == 'published') || github.event.inputs.release == 'true'
    name: update version number in documentation
    needs: [ export ]
    runs-on: ubuntu-latest
    steps:
      - run: python docs/update_version.py ${{ steps.version.outputs.version }} docs/source
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: updated version number in documentation
          file_pattern: docs/source/**