name: Build and test environment

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.yml'
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      constraint:
        description: which versions of dependencies to constrain
        required: true
        type: choice
        options:
          - stable
          - latest
          - dev
        default: latest
      release:
        description: upload exported files to a release of the current tag
        required: false
        type: boolean

defaults:
  run:
    shell: bash -l {0}

env:
  CRDS_PATH: /tmp/crds_cache
  PYSYN_CDBS: /tmp/trds

jobs:
  variables:
    name: set up environment variables
    runs-on: ubuntu-latest
    outputs:
      constraint: steps.constraint.outputs.constraint
    steps:
      - run: echo "constraint=$(if [ -z ${{ github.event.inputs.constraint }} ]; then echo latest; else echo ${{ github.event.inputs.constraint }}; fi)" >> $GITHUB_OUTPUT
        id: constraint
  build:
    name: build ${{ github.event.inputs.constraint }} Python ${{ matrix.python-version }} environment on ${{ matrix.os }}
    needs: [ variables ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.runs-on }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.constraint }}
          environment-file: stenv-${{ needs.variables.outputs.constraint }}.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - run: pip freeze
      - run: pytest -n auto tests/test_import.py
  unit_tests:
    name: run `${{ matrix.package }}` unit tests in ${{ github.event.inputs.constraint }} Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ variables, build ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        package: [ acstools, asdf, ccdproc, costools, jwst, reftools, synphot, wfpc2tools ]
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        include:
          - package: acstools
            extras: [ test ]
          - package: asdf
            extras: [ tests ]
          - package: ccdproc
            extras: [ test ]
          - package: costools
          - package: jwst
            extras: [ test ]
            env:
              CRDS_SERVER_URL: https://jwst-crds.stsci.edu
            pytest_args: '--slow'
          #- package: pysynphot
          #  extras: [ test ]
          - package: reftools
            extras: [ test ]
          - package: synphot
            extras: [ test ]
          - package: wfpc2tools
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.constraint }}
          environment-file: stenv-${{ needs.variables.outputs.constraint }}.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - if: matrix.extras != ''
        run: pip install "${{ matrix.package }}[${{ join(matrix.extras, ',') }}]"
      - if: matrix.commands != ''
        run: ${{ join(matrix.commands, ' && ') }}
      - run: pip freeze
      - if: matrix.env.CRDS_SERVER_URL != ''
        run: echo "context=$(crds list --operational-context)" >> $GITHUB_OUTPUT
        id: crds-context
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
      - if: steps.crds-context.outputs.context != ''
        uses: actions/cache@v3
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ matrix.package }}-${{ steps.crds-context.outputs.context }}
      - run: pytest -n auto ${{ matrix.pytest_args }} --pyargs ${{ matrix.package }}
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
  unit_tests_from_source:
    name: run `${{ matrix.package }}` unit tests from source in ${{ github.event.inputs.constraint }} Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ variables, build ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        package: [ calcos, hstcal, stsynphot ]
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        include:
          - package: calcos
            repository: spacetelescope/calcos
          #- package: crds
          #  repository: spacetelescope/crds
          #  extras: [ test ]
          #  env:
          #    CRDS_SERVER_URL: https://hst-crds.stsci.edu
          #  pre_command: './setup_test_cache $HOME && source envs/hst-crds-ops.sh &&'
          #- package: drizzlepac
          #  repository: spacetelescope/drizzlepac
          #  extras: [ test ]
          - package: hstcal
            repository: spacetelescope/hstcal
            pytest_args: '--slow'
            test_directory: tests
            env:
              CRDS_SERVER_URL: https://hst-crds.stsci.edu
          #- package: stistools
          #  repository: spacetelescope/stistools
          - package: stsynphot
            repository: spacetelescope/stsynphot_refactor
            extras: [ test ]
    steps:
      - uses: actions/checkout@v3
        with:
          path: stenv
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.constraint }}
          environment-file: stenv/stenv-${{ needs.variables.outputs.constraint }}.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - if: needs.variables.outputs.constraint != 'dev'
        run: echo "version=$(conda list | awk '$1 == "${{ matrix.package }}" {print $2}')" >> $GITHUB_OUTPUT
        id: package_version
        # TODO: figure out a better way to use package version when checking out a Git ref
      - uses: actions/checkout@v3
        with:
          path: ${{ matrix.package }}
          repository: ${{ matrix.repository }}
          ref: ${{ steps.package_version.outputs.version }}
      - if: matrix.extras != ''
        run: cd ${{ matrix.package }} && pip install ".[${{ join(matrix.extras, ',') }}]"
      - if: matrix.commands != ''
        run: cd ${{ matrix.package }} && ${{ join(matrix.commands, ' && ') }}
      - run: pip freeze
      - if: matrix.env.CRDS_SERVER_URL != ''
        run: echo "context=$(crds list --operational-context)" >> $GITHUB_OUTPUT
        id: crds-context
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
      - if: steps.crds-context.outputs.context != ''
        uses: actions/cache@v3
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ matrix.package }}-${{ steps.crds-context.outputs.context }}
      - run: cd ${{ matrix.package }} && ${{ matrix.pre_command }} pytest -n auto ${{ matrix.pytest_args }} ${{ matrix.test_directory }}
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
  smoke_tests:
    name: run `${{ matrix.package }}` smoke tests in ${{ github.event.inputs.constraint }} Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ variables, build ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        package: [ calcos, drizzlepac ]
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
        include:
          - package: calcos
            run: calcos la8n01qkq_rawtag_a.fits
            env:
              CRDS_SERVER_URL: https://hst-crds.stsci.edu
              jref: hst/references/hst/
          - package: drizzlepac
            run: pytest -n auto tests/test_drizzlepac.py
            env:
              CRDS_SERVER_URL: https://hst-crds.stsci.edu
              jref: hst/references/hst/
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.constraint }}
          environment-file: stenv-${{ needs.variables.outputs.constraint }}.yml
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python=${{ matrix.python-version }}
      - if: matrix.extras != ''
        run: pip install ".[${{ join(matrix.extras, ',') }}]"
      - if: matrix.commands != ''
        run: ${{ join(matrix.commands, ' && ') }}
      - run: pip freeze
      - if: matrix.env.CRDS_SERVER_URL != ''
        run: echo "context=$(crds list --operational-context)" >> $GITHUB_OUTPUT
        id: crds-context
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
      - if: steps.crds-context.outputs.context != ''
        uses: actions/cache@v3
        with:
          path: ${{ env.CRDS_PATH }}
          key: crds-${{ matrix.package }}-${{ steps.crds-context.outputs.context }}
      - uses: actions/cache@v3
        with:
          path: 'tests/data/'
          key: data-${{ hashFiles('tests/data/*') }}
      - run: ${{ matrix.run }}
        env:
          CRDS_SERVER_URL: ${{ matrix.env.CRDS_SERVER_URL }}
          jref: ${{ env.CRDS_PATH }}/${{ matrix.env.jref }}
  export:
    name: export ${{ github.event.inputs.constraint }} Python ${{ matrix.python-version }} environment on ${{ matrix.runs-on }}
    needs: [ variables, unit_tests, unit_tests_from_source, smoke_tests ]
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: sed -i"" -e "s/python/python==${{ matrix.python-version }}.*/g" stenv-${{ needs.variables.outputs.constraint }}.yml
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: mtkennerly/dunamai-action@v1
        id: version
        with:
          args: --pattern "(?P<base>\d+\.\d+\.\d+)"
      # TODO: change following to `provision-with-micromamba` after https://github.com/mamba-org/mamba/issues/2008
      - run: echo "::set-output name=date::$(date +'%a %b %d %Y')"
        id: date
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: stenv-${{ needs.variables.outputs.constraint }}.yml
          activate-environment: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.constraint }}
          python-version: ${{ matrix.python-version }}
          miniforge-version: 'latest'
          miniforge-variant: 'Mambaforge'
          use-mamba: true
          channels: 'conda-forge,defaults'
          channel-priority: true
          use-only-tar-bz2: true
      - uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/conda_pkgs_dir
            ${{ env.CONDA }}/envs/stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ needs.variables.outputs.constraint }}
          key: "mamba-env ${{ runner.os }}-${{ runner.arch }} ${{ steps.date.outputs.date }} file: ${{ hashFiles(format('stenv-{0}.yml', needs.variables.outputs.constraint)) }}"
      - run: conda env export --no-build > stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
      # TODO: change previous to `provision-with-micromamba` after https://github.com/mamba-org/mamba/issues/2008
      - run: |
          sed -i"" "/name:/d" stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
          sed -i"" "/prefix:/d" stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
      - run: cat stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
      - uses: actions/upload-artifact@v3
        with:
          name: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
          path: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
      - if: (github.event_name == 'release' && github.event.action == 'published') || github.event.inputs.release == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          file: stenv-${{ runner.os }}-py${{ matrix.python-version }}-${{ steps.version.outputs.version }}-${{ needs.variables.outputs.constraint }}.yml
