name: build

on:
  push:
    paths:
      - "**/*.yml"
  release:
    types:
      - published

defaults:
  run:
    shell: bash -l {0}

env:
  PYSYN_CDBS: /home/runner/trds

jobs:
  build:
    name: build environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: mtkennerly/dunamai-action@v1.1.0
        id: version
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ github.sha }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-latest
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - run: conda update --all
      - run: conda env export > spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - run: sed -i "s/spacetelescope-env-latest/spacetelescope-env-${{ steps.version.outputs.version }}/g" spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - run: cat spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: spacetelescope-env-${{ steps.version.outputs.version }}.yml
          path: spacetelescope-env-${{ steps.version.outputs.version }}.yml
  run_packaged_unit_tests:
    name: run `${{ matrix.package }}` unit tests
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: acstools
            dependencies: [ ci-watson, pytest-astropy-header, pytest-remotedata ]
          - package: ccdproc
            dependencies: [ memory_profiler, pytest-astropy ]
          - package: costools
            dependencies: [ ]
          - package: crds
            dependencies: [ lockfile, mock, nose, pylint ]
          #- package: nictools
          #  dependencies: [ ]
          - package: pysynphot
            dependencies: [ pytest-remotedata, pytest-astropy-header ]
          - package: reftools
            dependencies: [ pytest-remotedata, pytest-astropy-header ]
          - package: stsynphot
            dependencies: [ ci-watson, pytest-astropy ]
          - package: synphot
            dependencies: [ pytest-astropy ]
          #- package: wfc3tools
          #  dependencies: [ ]
          - package: wfpc2tools
            dependencies: [ ]
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ github.sha }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-latest
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - run: pip install pytest-xdist ${{ join(matrix.dependencies, ' ') }}
      - run: pytest -n auto --pyargs ${{ matrix.package }}
  run_repository_unit_tests:
    name: run `${{ matrix.package }}` unit tests
    needs: [ build ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: calcos
            repository: spacetelescope/calcos
            dependencies: [ ci_watson ]
            test_directory: tests
          - package: drizzlepac
            repository: spacetelescope/drizzlepac
            dependencies: [ ci-watson, crds, pytest-remotedata ]
            test_directory: tests
          - package: hstcal
            repository: spacetelescope/hstcal
            dependencies: [ ci-watson ]
            test_directory: tests
          - package: stistools
            repository: spacetelescope/stistools
            dependencies: [ ".[test]", six ]
            test_directory: tests
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          path: spacetelescope-env-distribution
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ github.sha }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-latest
          environment-file: spacetelescope-env-distribution/spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - uses: actions/checkout@v2.4.2
        with:
          path: ${{ matrix.package }}
          repository: ${{ matrix.repository }}
      - run: pip install pytest-xdist ${{ join(matrix.dependencies, ' ') }}
      - run: cd ${{ matrix.package }} && pytest -n auto ${{ matrix.test_directory }}
  run_calcos_smoke_tests:
    name: run `calcos` smoke tests
    needs: [ run_packaged_unit_tests, run_repository_unit_tests ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          lfs: true
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ github.sha }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-latest
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - uses: actions/cache@v3.0.4
        with:
          path: tests/data
          key: smoke-test-files-${{ hashFiles( 'tests/data/*' ) }}
      - run: calcos la8n01qkq_rawtag_a.fits
        env:
          lref: /grp/crds/hst/references/hst/
  run_drizzlepac_smoke_tests:
    name: run `drizzlepac` smoke tests
    needs: [ run_packaged_unit_tests, run_repository_unit_tests ]
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
        with:
          lfs: true
      - uses: actions/cache@v3.0.4
        with:
          path: |
            ~/conda_pkgs_dir
            /usr/share/miniconda/envs/spacetelescope-env-latest
          key: conda-${{ runner.os }}-${{ github.sha }}
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          activate-environment: spacetelescope-env-latest
          environment-file: spacetelescope-env-latest.yml
          use-only-tar-bz2: true
      - uses: actions/cache@v3.0.4
        with:
          path: tests/data
          key: smoke-test-files-${{ hashFiles( 'tests/data/*' ) }}
      - run: python tests/test_drizzlepac.py
        env:
          jref: /grp/crds/hst/references/hst/
  export:
    name: export environment
    needs: [ run_packaged_unit_tests, run_repository_unit_tests ]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: mtkennerly/dunamai-action@v1.1.0
        id: version
      - uses: dawidd6/action-download-artifact@v2.21.1
        with:
          name: spacetelescope-env-${{ steps.version.outputs.version }}.yml
          path: spacetelescope-env-${{ steps.version.outputs.version }}.yml
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          file: spacetelescope-env-${{ steps.version.outputs.version }}.yml
